#!/usr/bin/ruby

require 'socket'
require './variables.rb'
require './common.rb'

sock = UDPSocket.new
sock.bind("127.0.0.1", TX_PORT)
beacon_pkt = TetherBeacon.new(BEACON_TIME, 225)
state = :init

loop do
  case(state)
    when :init
      log state, "Sending beacon."
      sock.send_packet beacon_pkt
      frame = sock.recv_packet(BEACON_TIME/3)
      if(!frame) then
        log state, "No ack received so far, continuing."
        next
      end
      state = state_transition(state, :beaconing) if frame.packet.class == TetherAck
    when :beaconing
      sleep BEACON_TIME
      log state, "Sending beacon."
      sock.send_packet beacon_pkt
  end
end
